services:
  - type: web
    name: servicepower-to-housecall-bot
    env: python
    buildCommand: |
      pip install -r requirements.txt
      python -m playwright install --with-deps
    startCommand: python login_servicepower.py
